apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  labels:
    app: cart-service
spec:
  selector:
    matchLabels:
      app: cart-service
  replicas: 1
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: mikeroym/grpc-cart-service:latest
        imagePullPolicy: Always
        ports:
        - name: grpc-cart
          containerPort: 5001
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart-service
  ports:
  - port: 5001
    targetPort: grpc-cart
    protocol: TCP